"""
Transcript Summarizer — Generates Word documents from transcript files.

This script:
1. Reads all transcript .txt files from the transcripts/ directory
2. Sends each to a local LLM (Ollama) for summarization
3. Generates a structured Word document per course with chapter summaries

Usage:
    python summarize_to_docx.py --config config.yaml
    python summarize_to_docx.py --config config.yaml --course "rade-success-blueprint"
    python summarize_to_docx.py --config config.yaml --model llama3
"""

import argparse
import re
from pathlib import Path
from typing import Optional

import ollama
import yaml
from docx import Document
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

SUMMARY_PROMPT = """You are a technical learning assistant. Summarize the following video transcript into a clear, structured summary.

Instructions:
- Start with a brief 2-3 sentence overview of what the lesson covers
- List the key points and takeaways as bullet points
- Include any action items or assignments mentioned
- Note any tools, resources, or references mentioned
- Keep the summary concise but comprehensive (aim for 200-400 words)
- Use professional language suitable for a learning document

Transcript:
{transcript}

Summary:"""


def load_config(config_path: str) -> dict:
    """Load configuration from YAML file.

    Args:
        config_path: Path to the config.yaml file.

    Returns:
        Configuration dictionary.
    """
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def read_transcript(filepath: Path) -> tuple[str, str, str]:
    """Read a transcript file and extract metadata.

    Args:
        filepath: Path to the transcript .txt file.

    Returns:
        Tuple of (course_name, lesson_title, transcript_text).
    """
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    course_name = ""
    lesson_title = ""
    transcript_text = ""

    for i, line in enumerate(lines):
        if line.startswith("Course: "):
            course_name = line.replace("Course: ", "").strip()
        elif line.startswith("Lesson: "):
            lesson_title = line.replace("Lesson: ", "").strip()
        elif line.startswith("=" * 10):
            # Everything after the separator is the transcript
            transcript_text = "\n".join(lines[i + 1:]).strip()
            break

    # Fallback if no metadata header found
    if not transcript_text:
        transcript_text = content

    if not lesson_title:
        lesson_title = filepath.stem

    return course_name, lesson_title, transcript_text


def summarize_transcript(
    transcript: str,
    model: str = "llama3",
    base_url: Optional[str] = None,
) -> str:
    """Summarize a transcript using a local Ollama model.

    Args:
        transcript: The transcript text to summarize.
        model: Ollama model name to use.
        base_url: Optional custom Ollama server URL.

    Returns:
        Summary text generated by the LLM.
    """
    # Truncate very long transcripts to fit context window
    max_chars = 12000
    if len(transcript) > max_chars:
        transcript = transcript[:max_chars] + "\n\n[...transcript truncated for length...]"

    prompt = SUMMARY_PROMPT.format(transcript=transcript)

    try:
        client_kwargs = {}
        if base_url:
            client_kwargs["host"] = base_url

        client = ollama.Client(**client_kwargs)
        response = client.chat(
            model=model,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        )
        return response["message"]["content"].strip()
    except Exception as e:
        console.print(f"[red]Ollama error: {e}[/red]")
        console.print("[yellow]Make sure Ollama is running and the model is pulled.[/yellow]")
        console.print(f"[yellow]Run: ollama pull {model}[/yellow]")
        return f"[Summarization failed: {e}]"


def create_course_document(
    course_name: str,
    summaries: list[dict],
    output_dir: Path,
) -> Path:
    """Create a Word document with all lesson summaries for a course.

    Args:
        course_name: Name of the course.
        summaries: List of dicts with 'lesson_title', 'summary', and 'index'.
        output_dir: Directory to save the Word document.

    Returns:
        Path to the generated .docx file.
    """
    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Title
    title = doc.add_heading(f"{course_name}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Video Transcript Summaries")
    run.font.size = Pt(14)
    run.font.italic = True

    doc.add_paragraph()  # Spacer

    # Table of Contents
    doc.add_heading("Table of Contents", level=1)
    for item in summaries:
        toc_para = doc.add_paragraph(style="List Number")
        toc_para.add_run(item["lesson_title"])

    doc.add_page_break()

    # Individual lesson summaries
    for item in summaries:
        doc.add_heading(f"{item['index']}. {item['lesson_title']}", level=1)

        # Add summary content
        summary_lines = item["summary"].split("\n")
        for line in summary_lines:
            line = line.strip()
            if not line:
                continue

            # Detect bullet points
            if line.startswith("- ") or line.startswith("• ") or line.startswith("* "):
                bullet_text = re.sub(r"^[-•*]\s*", "", line)
                para = doc.add_paragraph(bullet_text, style="List Bullet")
            elif line.startswith("**") and line.endswith("**"):
                # Bold section headers within summary
                header_text = line.strip("*").strip()
                para = doc.add_paragraph()
                run = para.add_run(header_text)
                run.bold = True
            else:
                doc.add_paragraph(line)

        doc.add_paragraph()  # Spacer between lessons

    # Save document
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create filename from course name
    filename = re.sub(r"[^\w\s-]", "", course_name.lower())
    filename = re.sub(r"[\s_]+", "-", filename).strip("-")
    filepath = output_dir / f"{filename}-summary.docx"

    doc.save(str(filepath))
    return filepath


def discover_transcript_courses(transcripts_dir: Path, learning_dir: Optional[Path] = None) -> list[Path]:
    """Find all folders containing transcript files.

    Searches both the legacy transcripts/ directory and inside module folders
    under the learning/ directory.

    Args:
        transcripts_dir: Path to the legacy transcripts base directory.
        learning_dir: Root learning/ directory to search module folders.

    Returns:
        List of Paths to folders containing .txt transcript files.
    """
    found = []

    # Search legacy transcripts/ directory
    if transcripts_dir.exists():
        for d in transcripts_dir.iterdir():
            if d.is_dir() and any(d.glob("*.txt")):
                found.append(d)

    # Search inside module folders (learning/phase*/*/transcripts/)
    if learning_dir:
        for transcript_folder in learning_dir.rglob("transcripts"):
            if transcript_folder.is_dir() and any(transcript_folder.glob("*.txt")):
                if transcript_folder not in found:
                    found.append(transcript_folder)

    return sorted(found)


def process_course(
    course_folder: Path,
    model: str,
    ollama_url: Optional[str],
    output_dir: Path,
) -> Optional[Path]:
    """Process all transcripts in a course folder and generate a Word doc.

    Args:
        course_folder: Path to the course's transcript folder.
        model: Ollama model name.
        ollama_url: Optional custom Ollama server URL.
        output_dir: Directory to save the output Word document.

    Returns:
        Path to generated document, or None if no transcripts found.
    """
    transcript_files = sorted(course_folder.glob("*.txt"))
    if not transcript_files:
        console.print(f"[yellow]No transcript files in {course_folder.name}[/yellow]")
        return None

    console.print(f"\n[bold cyan]Summarizing: {course_folder.name}[/bold cyan]")
    console.print(f"  Found {len(transcript_files)} transcript(s)")

    summaries = []

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        task = progress.add_task("Summarizing...", total=len(transcript_files))

        for i, filepath in enumerate(transcript_files, 1):
            course_name, lesson_title, transcript_text = read_transcript(filepath)
            progress.update(task, description=f"[{i}/{len(transcript_files)}] {lesson_title[:50]}")

            if not transcript_text or len(transcript_text) < 20:
                console.print(f"  [yellow]Skipping (too short):[/yellow] {filepath.name}")
                progress.advance(task)
                continue

            # Summarize using local LLM
            summary = summarize_transcript(transcript_text, model=model, base_url=ollama_url)

            summaries.append({
                "index": i,
                "lesson_title": lesson_title or filepath.stem,
                "summary": summary,
            })

            console.print(f"  [green]Summarized:[/green] {lesson_title[:60]}")
            progress.advance(task)

    if not summaries:
        console.print("[yellow]No valid transcripts to summarize[/yellow]")
        return None

    # Use the course name from the first transcript, or folder name as fallback
    display_name = course_name if course_name else course_folder.name.replace("-", " ").title()

    # Generate Word document
    doc_path = create_course_document(display_name, summaries, output_dir)
    console.print(f"  [bold green]Generated:[/bold green] {doc_path}")

    return doc_path


def main():
    """Main entry point for the transcript summarizer."""
    parser = argparse.ArgumentParser(
        description="Summarize video transcripts into Word documents using a local LLM"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="config.yaml",
        help="Path to config.yaml file (default: config.yaml)",
    )
    parser.add_argument(
        "--course",
        type=str,
        default=None,
        help="Process only a specific course folder (by name)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Override Ollama model name from config",
    )
    args = parser.parse_args()

    # Load config
    config_path = Path(args.config)
    if not config_path.exists():
        config_path = Path(__file__).parent / args.config
    if not config_path.exists():
        console.print(f"[red]Config file not found: {args.config}[/red]")
        return

    config = load_config(str(config_path))

    # Resolve paths
    transcripts_dir = Path(
        config.get("output_dir", str(Path(__file__).parent.parent / "transcripts"))
    )
    output_dir = Path(
        config.get("docx_output_dir", str(Path(__file__).parent.parent / "output"))
    )

    # LLM settings
    model = args.model or config.get("ollama", {}).get("model", "llama3")
    ollama_url = config.get("ollama", {}).get("base_url", None)

    console.print("[bold]RADE Transcript Summarizer[/bold]")
    console.print(f"Model: {model}")
    console.print(f"Transcripts: {transcripts_dir}")
    console.print(f"Output: {output_dir}")
    console.print()

    # Discover transcript folders (in module folders and legacy transcripts/)
    learning_dir = Path(__file__).parent.parent  # learning/ folder
    courses = discover_transcript_courses(transcripts_dir, learning_dir=learning_dir)
    if not courses:
        console.print("[red]No transcript folders found.[/red]")
        console.print(f"Run crawl_transcripts.py first to extract transcripts.")
        return

    # Filter if specified
    if args.course:
        courses = [c for c in courses if args.course.lower() in str(c).lower()]
        if not courses:
            console.print(f"[red]No course matching '{args.course}' found[/red]")
            return

    console.print(f"Courses to process: {len(courses)}")
    for c in courses:
        console.print(f"  - {c}")

    # Process each course
    generated_docs = []
    for course_folder in courses:
        doc_path = process_course(course_folder, model, ollama_url, output_dir)
        if doc_path:
            generated_docs.append(doc_path)

    # Final summary
    console.print(f"\n[bold green]Done! Generated {len(generated_docs)} document(s)[/bold green]")
    for doc in generated_docs:
        console.print(f"  {doc}")


if __name__ == "__main__":
    main()
